version: '3.8'

services:
   # -------------------- Kafka Topic Init --------------------
  kafka-init:
    image: docker.io/bitnami/kafka:3.7
    container_name: blog-kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: >
      bash -c "
        echo 'Waiting for Kafka to be ready...' &&
        sleep 5 &&
        kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic comment_topic --partitions 1 --replication-factor 1 &&
        echo 'Topic comment_topic created' &&
        sleep 2
      "
    networks:
      - blog-network

  # -------------------- Go 应用 --------------------
  go-app:
    build: .
    container_name: my-blog-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=blogdb
      - ETCD_ENDPOINTS=etcd:2379
      - KAFKA_BROKERS=kafka:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      kafka-init:
        condition: service_completed_successfully  # 等 topic 创建完成后再启动
      mysql:
        condition: service_healthy
      etcd:
        condition: service_started
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure
    networks:
      - blog-network

  # -------------------- MySQL --------------------
  mysql:
    image: mysql:8.0
    container_name: blog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: blogdb
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 5s
      timeout: 10s
      retries: 5

  # -------------------- etcd --------------------
  etcd:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: blog-etcd
    environment:
      - ETCD_NAME=node1
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_INITIAL_CLUSTER=node1=http://etcd:2380
    ports:
      - "12379:2379"
      - "12380:2380"
    volumes:
      - etcd-data:/etcd-data
    command: /usr/local/bin/etcd
    networks:
      - blog-network

  # -------------------- Kafka --------------------
  kafka:
    image: docker.io/bitnami/kafka:3.7
    container_name: blog-kafka
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "19092:9092"
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - blog-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  # -------------------- Redis --------------------
  redis:
    image: redis:7-alpine
    container_name: blog-redis
    ports:
      - "6379:6379"
    networks:
      - blog-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  blog-network:
    driver: bridge

volumes:
  mysql-data:
  etcd-data:
  kafka-data: